### ISSUE TITLE
Virtual disk cache setting to none causes data corruption on power loss

### ISSUE THREAD

**Issue by Aidam** [tteck/Proxmox#1172]
**Describe the issue**
I think the script should set the virtual disk to cache=writetrough on default

Based on this section of proxmox wiki:  https://pve.proxmox.com/wiki/Performance_Tweaks#Disk_Cache , current setting of cachce= none can cause data loss on power loss. 

In my instance, the data partition of HAOS went unusable and unrepairable every time there was a power outage.while the physical SSD and proxmox installation remained intact.  After studying the wiki and changing the caching settings to writethrough, there is no data corruption/loss on power outage .  

Other than that, the script is really helpful, thanks

**Comment by tteck** [comment]
I have not come across this problem before. The cache=none option appears to provide the best performance and has been the default since Proxmox 2.X. On the other hand, the cache=Writethrough option ensures greater data security as it performs an fsync for every write. However, this option is slower. It might be worth considering adding it as an advanced setting option.
