### ISSUE TITLE
NginxProxyManager 2.10.0 not installing, remains on 2.9.22

### ISSUE THREAD

**Issue by wokkeltje13** [tteck/Proxmox#1265]
The NginxProxyManager install/update script remains on version 2.9.22 instead of the new 2.10

But things have changed according the changelog
https://github.com/NginxProxyManager/nginx-proxy-manager/releases

tnx in advance for the useful scripts you make.

**Comment by tteck** [comment]
Since version 2.10 is causing installation disruptions, I will continue to use v2.9.22  https://github.com/tteck/Proxmox/commit/ec432fce345e6fabd29afd068bf0edcb42e15cb0 until I can allocate time to rewrite the script.

Let's wait for them to work out their issues first.
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2753

**Comment by tteck** [comment]
Fixed

**Comment by wokkeltje13** [comment]
Tnx, but now I experience a NGINX proxy manager issue https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2771. 
But this is not an issue you can fix.

**Comment by wokkeltje13** [comment]
Is this something you need to change in your install script?
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2774

**Comment by tteck** [comment]
Based on the information provided, it seems unlikely that the issue is caused by the database system being used. The script is using SQLite.
