### ISSUE TITLE
Bitwarden update failed with apk command

### ISSUE THREAD

**Issue by leranp** [tteck/Proxmox#1617]
### A clear and concise description of the issue.

Trying to run the update script inside the LXC is failed 

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Loading...
environment: line 56: apk: command not found
[ERROR] in line 56: exit code 127: while executing

### Please provide detailed steps to reproduce the issue.

bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-vaultwarden.sh)"

**Comment by tteck** [comment]
Wrong script?

**Comment by tteck** [comment]
If you're utilizing the Alpine installation of Vaultwarden, there shouldn't be any problem.

```
 _    __            ____                          __         
| |  / /___ ___  __/ / /__      ______ __________/ /__  ____ 
| | / / __ `/ / / / / __/ | /| / / __ `/ ___/ __  / _ \/ __ \
| |/ / /_/ / /_/ / / /_ | |/ |/ / /_/ / /  / /_/ /  __/ / / /
|___/\__,_/\__,_/_/\__/ |__/|__/\__,_/_/   \__,_/\___/_/ /_/ 
 Alpine                                                 

fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
v3.18.0-6053-g5ed4e88f5d7 [https://dl-cdn.alpinelinux.org/alpine/edge/main]
v3.18.0-6059-g39d115ed4c7 [https://dl-cdn.alpinelinux.org/alpine/edge/community]
v3.18.0-6058-gcb34e163675 [https://dl-cdn.alpinelinux.org/alpine/edge/testing]
OK: 28560 distinct packages available
(1/17) Upgrading musl (1.2.4-r2 -> 1.2.4-r5)
(2/17) Upgrading busybox (1.36.1-r2 -> 1.36.1-r3)
Executing busybox-1.36.1-r3.post-upgrade
(3/17) Upgrading busybox-binsh (1.36.1-r2 -> 1.36.1-r3)
(4/17) Upgrading openrc (0.47.1-r3 -> 0.48-r0)
Executing openrc-0.48-r0.post-upgrade
(5/17) Upgrading busybox-mdev-openrc (1.36.1-r2 -> 1.36.1-r3)
(6/17) Upgrading ssl_client (1.36.1-r2 -> 1.36.1-r3)
(7/17) Upgrading busybox-openrc (1.36.1-r2 -> 1.36.1-r3)
(8/17) Upgrading busybox-suid (1.36.1-r2 -> 1.36.1-r3)
(9/17) Upgrading musl-utils (1.2.4-r2 -> 1.2.4-r5)
(10/17) Upgrading ncurses-terminfo-base (6.4_p20230701-r0 -> 6.4_p20230708-r1)
(11/17) Upgrading libncursesw (6.4_p20230701-r0 -> 6.4_p20230708-r1)
(12/17) Upgrading nghttp2-libs (1.54.0-r0 -> 1.55.0-r0)
(13/17) Upgrading glib (2.76.3-r0 -> 2.76.4-r0)
(14/17) Upgrading libgcc (13.1.1_git20230701-r0 -> 13.1.1_git20230708-r0)
(15/17) Upgrading vaultwarden (1.28.1-r4 -> 1.29.0-r1)
(16/17) Upgrading vaultwarden-openrc (1.28.1-r4 -> 1.29.0-r1)
(17/17) Upgrading vaultwarden-web-vault (1.28.1-r4 -> 1.29.0-r1)
Executing busybox-1.36.1-r3.trigger
Executing glib-2.76.4-r0.trigger
OK: 96 MiB in 74 packages
alpine-vaultwarden:~# 
```

**Comment by leranp** [comment]
How can I utilize the Alpine installation?

**Comment by tteck** [comment]
> How can I utilize the Alpine installation?

By following the instructions
![Screenshot 2023-07-14 8 25 56 AM](https://github.com/tteck/Proxmox/assets/21342670/37d824de-9730-4545-b054-e4b19d05ad17)

Since this issue is not directly related to the script itself, but rather the choice of script, it is considered closed.

**Comment by Toxo666** [comment]
Hello @leranp 
I have an answer for you. I had the same problem.
The error comes, because of the customization folder of web-vault in /etc/conf.d/vaultwarden.

This is `export WEB_VAULT_FOLDER=/var/lib/vaultwarden/web-vault`
In standard apk vaultwarden(-web-vault) package it is: `export WEB_VAULT_FOLDER=/usr/share/webapps/vaultwarden-web/`

To fix this error you can do the following.
Stopping vaultwarden `rc-service vaultwarden stop`

`cp -a /etc/conf.d/vaultwarden /etc/conf.d/vaultwarden.backup`
`nano /etc/conf.d/vaultwarden` #change the web vault folder line to export WEB_VAULT_FOLDER=/usr/share/webapps/vaultwarden-web/
`apk fix vaultwarden` #so you have an /etc/conf.d/vaultwarden.apk-fix file with original config
`apk -U upgrade`
`apk add vaultwarden-web-vault`
`rc-service vaultwarden restart`

this should also work in future updates.
Greets
toxo
