### ISSUE TITLE
Transmission LXC hangs

### ISSUE THREAD

**Issue by thealphonso** [tteck/Proxmox#1702]
### A clear and concise description of the issue.

Every couple of days I notice that the Transmission LXC hangs and I cannot connect to it anymore. The memory usage is at maximum (both swap and RAM); also the CPU usage is around 50%.
Allocated resources are CPU: 2, RAM 4GB, Swap: 512MB on an Intel NUC 11 running Proxmox 8.0.4

**Comment by tteck** [comment]
I apologize for the difficulties you're facing with the application. However, my main focus is centered around developing application LXCs, and I'm not specialized in providing assistance for issues that arise during the operation of these applications. 

I recommend that you share your issue on the [discussions forum](https://github.com/tteck/Proxmox/discussions). This way, you can potentially receive help from individuals who are more proficient and qualified in addressing such matters.

Since this matter is not connected to the script, it is now considered closed.
