### ISSUE TITLE
ChangeDetection Takes A Long Time To Shutdown

### ISSUE THREAD

**Issue by alwaysmod** [tteck/Proxmox#1882]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After installing ChangeDetection, it takes a long time to restart or shutdown. Which in-turn delays the restart/shutdown process of Proxmox.

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

Install via script, setup to monitor at least one site then try shutting down the LXC.

**Comment by tteck** [comment]
The speed at which a system shuts down primarily depends on the services and processes that must be halted or concluded during shutdown. One potential method to influence the shutdown duration is to experiment with the following configuration in both service files:
```
[Service]
TimeoutStopSec=30s
```
This setting allows the service 30 seconds to shut down gracefully; if it doesn't, it will be forcibly terminated. I prefer not to forcibly shut down a functioning application. 

As this issue is unrelated to the script, it is considered closed.
