### ISSUE TITLE
haos-vm-v3.sh - Needs new default value to run without error

### ISSUE THREAD

**Issue by kinsaiduck** [tteck/Proxmox#241]
I dont't know if a new update of proxmox changed something in the default values, but I ran into an issue using the haos-vm-v3.sh script.

Before starting the vm I had to disable the following setting in the vm options"kvm hardware virtualization", otherwise the script ran into an error starting the generated vm. 

I suggest disabling this setting when using the default installation of the skript.

**Comment by tteck** [comment]
KVM hardware virtualization support should almost always be turned on. This option is going to use your CPU's hardware support for virtualization, which will give you near baremetal performance inside your VM. Turning it off will force your CPU to emulate that virtualization in software, which comes with severe performance penalties

The only reason the option is there at all is because some older processors don't support this, and you have to emulate it. This manifests as a VM with hardware virtualization turned on refusing to boot, If that happens, either your processor doesn't support it, or it's turned off in your BIOS.

**Comment by kinsaiduck** [comment]
Oh, I see. I wasn't aware of that. Sorry for the inconvenience. 
Thank you for pointing that out, I will check my bios for that.
