### ISSUE TITLE
Docker Alpine LXC runtime issue

### ISSUE THREAD

**Issue by archuser123445** [tteck/Proxmox#2717]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When running the alpine installation script, i receive the following error:

```bash
Executing busybox-1.36.1-r15.trigger
OK: 291 MiB in 81 packages
 * Caching service dependencies ...                                                                                                            [ ok ]
mount: mounting none on /sys/fs/cgroup failed: Resource busy
sh: write error: Resource busy
sh: write error: Resource busy
sh: write error: Resource busy
sh: write error: Resource busy
sh: write error: Resource busy
sh: write error: Resource busy
sh: write error: Resource busy
sh: write error: Resource busy
sh: error setting limit: Operation not permitted
 * docker: unable to apply RC_ULIMIT settings
 * /var/log/docker.log: creating file
 * /var/log/docker.log: correcting owner
 * Starting Docker Daemon ...                                                                                                                  [ ok ]
 * service docker added to runlevel default
 ✓ Installed Docker

[ERROR] in line 34: exit code 1: while executing command DOCKER_COMPOSE_LATEST_VERSION=$(get_latest_release "docker/compose")
```

Thanks so much for the scripts!

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

run:
```bash
bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-docker.sh)"
```

**Comment by archuser123445** [comment]
I receive the same error in both, however that is the output from verbose mode

**Comment by tteck** [comment]
🏁 The script runs without any problems from this end.

```
    ____             __            
   / __ \____  _____/ /_  __  _____
  / / / / __ \/ ___/ //_/ _ \/ ___/
 / /_/ / /_/ / /__/ ,< /  __/ /    
/_____/\____/\___/_/|_|\___/_/     
 Alpine
 
Using Advanced Settings
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: alpine-docker
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 1024
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Alpine-Docker LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Docker
Would you like to add Portainer? <y/N> y
 ✓ Installed Portainer 2.19.4
Would you like to add Docker Compose? <y/N> y
 ✓ Installed Docker Compose v2.26.1
 ✓ Customized Container
 ✓ Completed Successfully!
```

**Comment by tteck** [comment]
The error message `mount: mounting none on /sys/fs/cgroup failed: Resource busy` suggests that there might be an issue with mounting the cgroup filesystem. This could be due to various reasons such as conflicting mounts or processes holding onto resources.

The subsequent `sh: write error: Resource busy` messages indicate that there were write errors, possibly due to the system being busy or resources being locked.

The error `sh: error setting limit: Operation not permitted` suggests that there might be permission issues when trying to set limits, possibly due to insufficient privileges.

Despite these errors, Docker seems to have been installed successfully and the Docker daemon has been started.

For the error `[ERROR] in line 34: exit code 1: while executing command DOCKER_COMPOSE_LATEST_VERSION=$(get_latest_release "docker/compose")`

If you copy the command below (from the script) and paste it in the Proxmox shell, it should return the versions

```
get_latest_release() {
    curl -sL "https://api.github.com/repos/$1/releases/latest" | grep '"tag_name":' | cut -d'"' -f4
}

PORTAINER_LATEST_VERSION=$(get_latest_release "portainer/portainer")
DOCKER_COMPOSE_LATEST_VERSION=$(get_latest_release "docker/compose")
PORTAINER_AGENT_LATEST_VERSION=$(get_latest_release "portainer/agent")

echo "Portainer $PORTAINER_LATEST_VERSION"
echo "Docker Compose $DOCKER_COMPOSE_LATEST_VERSION"
echo "Portainer Agent $PORTAINER_AGENT_LATEST_VERSION"
```
https://github.com/tteck/Proxmox/blob/90463f5aafbbf31c4b431cc19801a80a2aadc3e4/install/alpine-docker-install.sh#L30-L35

Here's the output that I get when executing the command in the Proxmox shell

```
Portainer 2.19.4
Docker Compose v2.26.1
Portainer Agent 1.6.1
```

If you'd like to provide information about your setup, and how you're executing the command, may give more insight into the issues you encountered.

🧐 As this issue is unrelated to the script, it is considered closed.

**Comment by tteck** [comment]
If you'd like to provide information about your setup, and how you're executing the command, may give more insight into the issues you encountered.
