### ISSUE TITLE
Unable to update scrypted through the script.

### ISSUE THREAD

**Issue by hasrt1206** [tteck/Proxmox#3236]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When trying to update scrypted through the script I get the error saying No Scrypted installation found!

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![No Scrypted](https://github.com/tteck/Proxmox/assets/69708609/925b9e17-8591-4695-89e0-ec8744580ea0)

### Please provide detailed steps to reproduce the issue.

1. Go to this website (https://tteck.github.io/Proxmox/?id=AgentDVR#scrypted-lxc)
2. Copy this script `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/scrypted.sh)"`
3. Go to my lxc conatiner on my proxmox server
4. Paste this script `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/scrypted.sh)"`

**Comment by Mellowlynx** [comment]
Did you run the command from within the console of the LXC?

**Comment by Mellowlynx** [comment]
It looks like the **_scrypted.service_** does not exist within the LXC, did you make any custom changes?
You could update by manually, just run `apt update && apt upgrade -y`

**Comment by tteck** [comment]
The script creates `/etc/systemd/system/scrypted.service` during creation.
https://github.com/tteck/Proxmox/blob/53b24ef7b77f38a77d8ba3ba4b7bd6c458d4f1d5/install/scrypted-install.sh#L110

The script looks for that file
https://github.com/tteck/Proxmox/blob/53b24ef7b77f38a77d8ba3ba4b7bd6c458d4f1d5/ct/scrypted.sh#L58


🧐 As this issue is unrelated to the script, it is considered closed.
