### ISSUE TITLE
Post Install script <Y/n> default incorrect

### ISSUE THREAD

**Issue by ajayrgb** [tteck/Proxmox#334]
For all the <Y/n> prompts in the post install script, pressing enter without typing anything selects No.  I would expect the capitalized option to be the default when pressing enter.

**Comment by tteck** [comment]
Your expectations were wrong
```
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
```

**Comment by CartCaved** [comment]
I think as mentioned by @ajayrgb in #326, the capitalized letter is often (usually) expected to be what is chosen by pressing enter. That means that some users (including myself) will believe that the script will pick the capitilized option when pressing Enter and therefore get the incorrect result.

But I don't think the OP intende the script behaviour to change. No is (probably) a good default. I think the suggestion here is to change the scripts to capitalize N instead of Y to prevent users from making the wrong assumptions.

The alternative is to have neither letter in capital (less understandable as there is a default) or to write out "Enter selects the no option" .

**Comment by tteck** [comment]
Has already been changed to lower case

**Comment by CartCaved** [comment]
That was fast! Sorry for the spamming then, misunderstood your closing comment and label.
