### ISSUE TITLE
Typo in URL "$var_install.sh" vs. "$var-install.sh"

### ISSUE THREAD

**Issue by Grantelbert0815** [tteck/Proxmox#3882]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

There is a Typo **_** vs. **-** here

https://github.com/tteck/Proxmox/blob/6fbb8ab4a218638ca1c8c01f12ab0657c0f4a39b/misc/build.func#L636C51-L636C127

This URL doesn't exist.
https://raw.githubusercontent.com/tteck/Proxmox/main/install/$var_install.sh

Should be replaced by 
https://raw.githubusercontent.com/tteck/Proxmox/main/install/$var-install.sh

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

  lxc-attach -n "$CTID" -- bash -c "$(wget -qLO - https://raw.githubusercontent.com/tteck/Proxmox/main/install/$var_install.sh)" || exit

**Comment by MickLesk** [comment]
I don't think this is an error because var_install is just a variable and is replaced with ${NSAPP}-install. 
NSAPP-install can be e.g. “mqtt” -> mqtt-install
which means that https://raw.githubusercontent.com/tteck/Proxmox/main/install/mqtt-install.sh is then called


https://github.com/tteck/Proxmox/blob/6fbb8ab4a218638ca1c8c01f12ab0657c0f4a39b/misc/build.func#L1-L4
