### ISSUE TITLE
After rebooting, Unifi LXC just displays 404

### ISSUE THREAD

**Issue by mon5termatt** [tteck/Proxmox#451]
after reboot the server does not load 
all pages show:
HTTP Status 404 – Not Found

![image](https://i.imgur.com/1xKvcFp.png)

**Comment by tteck** [comment]
Did the IP change after reboot?
In the LXC console run `hostname -I`

**Comment by mon5termatt** [comment]
@tteck it looks like im not alone https://github.com/linuxserver/docker-unifi-controller/issues?q=404

**Comment by tteck** [comment]
WOW, run these lines in the LXC console

```
apt remove unifi
```
```
echo 'deb https://www.ui.com/downloads/unifi/debian stable ubiquiti' | sudo tee /etc/apt/sources.list.d/100-ubnt-unifi.list
```
```
wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ui.com/unifi/unifi-repo.gpg 
```
```
apt-get update && apt-get install unifi -y
```

should fix the issue 🤞🏻

**Comment by mon5termatt** [comment]
Still takes a minute to come up after reboot, but only like 30 seconds now. Which is a lot better than it was before, thanks!

**Comment by bruno-dogancic** [comment]
Hey @tteck 

This one saved me, is it possible to add this type of instruction to the installation page as an update section of sorts?

Other stuff has nice instruction on how to update.

Thank you for putting in the hard work!

**Comment by bruno-dogancic** [comment]
@tteck Also, do you know what could be the reason for not being able to use HA Unifi Network application integration?

When I ran it barebone on some old laptop with linux mint it worked.

I have since switched to home assistant VM and unifi network application LXC using your scripts, and cannot get the HA Network application integration to work.

I haven't changed any settings in my unifi as I used backup from that old setup and now even updated it to the latest version

p.s I can ping the unifi ip address from home assistant terminal with no problem

**Comment by tteck** [comment]
I don't utilize Unifi, so I'll be no help there. Ask in discussions, I'm sure someone has the answer.

**Comment by bruno-dogancic** [comment]
> I don't utilize Unifi, so I'll be no help there. Ask in discussions, I'm sure someone has the answer.

Ok, wow, by accident I stumbled upon [this](https://community.home-assistant.io/t/unifi-network-failed-to-connect/435468/30), so if anyone will need: change the port from the default 443 to **8443**
